name = "NMRPulses"
uuid = "52b8e669-ab82-46f0-ac95-a84aece7faa1"
authors = ["Alastair <alastair@nvision-imaging.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
